## Netlify Redirects
[[redirects]]
  from = "/kiosk-kultur"
  to = "/kiosk-kultur/"
  status = 301
  force = false

[[redirects]]
  from = "/kiosk-kultur/*"
  to = "https://fs-kisok-kultur-01.netlify.app/:splat"
  status = 200
  force = true